"""add is_passed field to team submission

Revision ID: 01298ae0ce45
Revises: 1d440e5fa11f
Create Date: 2026-03-06 15:09:24.488995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '01298ae0ce45'
down_revision: Union[str, Sequence[str], None] = '1d440e5fa11f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_passed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_submissions', schema=None) as batch_op:
        batch_op.drop_column('is_passed')

    # ### end Alembic commands ###
