"""mentors get assigned to helpers

Revision ID: 118e124ca47d
Revises: 6e86e1548ad6
Create Date: 2026-03-14 01:34:12.897938

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '118e124ca47d'
down_revision: Union[str, Sequence[str], None] = '6e86e1548ad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
