"""add submission entity

Revision ID: 11a82c0d6b6f
Revises: d17cdc616a7b
Create Date: 2026-02-25 23:34:59.554203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11a82c0d6b6f'
down_revision: Union[str, Sequence[str], None] = 'd17cdc616a7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('submission_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_team_submissions_category_id_categories')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_submissions_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_submissions'))
    )
    with op.batch_alter_table('team_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_submissions_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_submissions_team_id'), ['team_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_submissions_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_submissions_category_id'))

    op.drop_table('team_submissions')
    # ### end Alembic commands ###
