"""final group membership

Revision ID: 1bd2147b4718
Revises: 2f80edc22397
Create Date: 2026-03-08 14:09:39.747520

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "1bd2147b4718"
down_revision: Union[str, Sequence[str], None] = "2f80edc22397"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("participants", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_telegram_final_group_member",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("participants", schema=None) as batch_op:
        batch_op.drop_column("is_telegram_final_group_member")

    # ### end Alembic commands ###
