"""mentorship sessions + final group membership

Revision ID: 2f80edc22397
Revises: 01298ae0ce45
Create Date: 2026-03-08 13:59:59.974522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '2f80edc22397'
down_revision: Union[str, Sequence[str], None] = '01298ae0ce45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_handle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_mentors_category_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mentors'))
    )
    with op.batch_alter_table('mentors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mentors_telegram_handle'), ['telegram_handle'], unique=True)

    op.create_table('mentorship_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('slot_start', sa.DateTime(), nullable=False),
    sa.Column('slot_end', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentors.id'], name=op.f('fk_mentorship_sessions_mentor_id_mentors')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_mentorship_sessions_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mentorship_sessions'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mentorship_sessions')
    with op.batch_alter_table('mentors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mentors_telegram_handle'))

    op.drop_table('mentors')
    # ### end Alembic commands ###
