"""helper functionality

Revision ID: 3346aa6c2b97
Revises: 3f1c6c5a913d
Create Date: 2026-03-13 19:04:54.185147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '3346aa6c2b97'
down_revision: Union[str, Sequence[str], None] = '3f1c6c5a913d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('helpers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_handle', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_helpers')),
    sa.UniqueConstraint('telegram_user_id', name=op.f('uq_helpers_telegram_user_id'))
    )
    with op.batch_alter_table('helpers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_helpers_telegram_handle'), ['telegram_handle'], unique=True)

    op.create_table('helper_availability_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('helper_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('slot_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('slot_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_helper_availability_slots_category_id_categories')),
    sa.ForeignKeyConstraint(['helper_id'], ['helpers.id'], name=op.f('fk_helper_availability_slots_helper_id_helpers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_helper_availability_slots')),
    sa.UniqueConstraint('helper_id', 'slot_start', 'slot_end', name=op.f('uq_helper_availability_slots_helper_id'))
    )
    op.create_table('session_helper_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('helper_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('assigned_by', sa.BigInteger(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['helper_id'], ['helpers.id'], name=op.f('fk_session_helper_assignments_helper_id_helpers')),
    sa.ForeignKeyConstraint(['session_id'], ['mentorship_sessions.id'], name=op.f('fk_session_helper_assignments_session_id_mentorship_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_helper_assignments')),
    sa.UniqueConstraint('session_id', name=op.f('uq_session_helper_assignments_session_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_helper_assignments')
    op.drop_table('helper_availability_slots')
    with op.batch_alter_table('helpers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_helpers_telegram_handle'))

    op.drop_table('helpers')
    # ### end Alembic commands ###
