"""sync mentorship category to db

Revision ID: 468b82ebed44
Revises: 80996bca5e07
Create Date: 2026-03-12 15:13:05.932395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '468b82ebed44'
down_revision: Union[str, Sequence[str], None] = '80996bca5e07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_mentorship_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('group_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('session_duration', sa.Integer(), nullable=False),
    sa.Column('session_gap', sa.Integer(), nullable=False),
    sa.Column('min_session_count', sa.Integer(), nullable=False),
    sa.Column('max_session_count', sa.Integer(), nullable=False),
    sa.Column('assignment_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('schedule_json', sa.Text(), nullable=False),
    sa.Column('whatever_config_json', sa.Text(), nullable=True),
    sa.Column('strict_config_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_category_mentorship_configs_category_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category_mentorship_configs')),
    sa.UniqueConstraint('category_id', name=op.f('uq_category_mentorship_configs_category_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category_mentorship_configs')
    # ### end Alembic commands ###
