"""different scheduling

Revision ID: 48a7f9f7405f
Revises: 118e124ca47d
Create Date: 2026-03-14 08:15:06.275356

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '48a7f9f7405f'
down_revision: Union[str, Sequence[str], None] = '118e124ca47d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
