"""Fixing tables

Revision ID: 4d63f0032267
Revises: 31031020e2a4
Create Date: 2026-01-10 21:07:17.738250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '4d63f0032267'
down_revision: Union[str, Sequence[str], None] = '31031020e2a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=False))
        batch_op.alter_column('telegram',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('study_year',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('university_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('fk_participants_preferred_category_id_categories'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_participants_category_id_categories'), 'categories', ['category_id'], ['id'])
        batch_op.drop_column('photo_consent')
        batch_op.drop_column('preferred_category_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_category_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('photo_consent', sa.BOOLEAN(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_participants_category_id_categories'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_participants_preferred_category_id_categories'), 'categories', ['preferred_category_id'], ['id'])
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('university_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('study_year',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('telegram',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
