"""default helper link

Revision ID: 65fbc206df40
Revises: 48a7f9f7405f
Create Date: 2026-03-14 12:19:02.234224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '65fbc206df40'
down_revision: Union[str, Sequence[str], None] = '48a7f9f7405f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('helpers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_meeting_link', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('helpers', schema=None) as batch_op:
        batch_op.drop_column('default_meeting_link')

    # ### end Alembic commands ###
