"""helper group assignemnt

Revision ID: 6e86e1548ad6
Revises: 3346aa6c2b97
Create Date: 2026-03-13 21:50:03.519762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '6e86e1548ad6'
down_revision: Union[str, Sequence[str], None] = '3346aa6c2b97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_mentorship_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('helper_group_chat_id', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_mentorship_configs', schema=None) as batch_op:
        batch_op.drop_column('helper_group_chat_id')

    # ### end Alembic commands ###
