"""group activation and topic split, and meeting linksand reminders

Revision ID: 80996bca5e07
Revises: 9b2a826b55f3
Create Date: 2026-03-12 02:33:22.419110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '80996bca5e07'
down_revision: Union[str, Sequence[str], None] = '9b2a826b55f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forwarded_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('source_message_id', sa.Integer(), nullable=False),
    sa.Column('target_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('target_message_id', sa.Integer(), nullable=False),
    sa.Column('direction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forwarded_messages'))
    )
    with op.batch_alter_table('forwarded_messages', schema=None) as batch_op:
        batch_op.create_index('ix_fwd_source', ['source_chat_id', 'source_message_id'], unique=False)
        batch_op.create_index('ix_fwd_target', ['target_chat_id', 'target_message_id'], unique=False)

    op.create_table('activated_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('activated_by', sa.BigInteger(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_activated_groups_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activated_groups')),
    sa.UniqueConstraint('chat_id', name=op.f('uq_activated_groups_chat_id')),
    sa.UniqueConstraint('team_id', name=op.f('uq_activated_groups_team_id'))
    )
    op.create_table('group_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('mentor_group_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('topic_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_group_topics_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_topics')),
    sa.UniqueConstraint('mentor_group_chat_id', 'team_id', name=op.f('uq_group_topics_mentor_group_chat_id'))
    )
    with op.batch_alter_table('mentors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participation_format', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('mentor_group', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('default_meeting_link', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    with op.batch_alter_table('mentorship_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meeting_link', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('reminder_sent', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentorship_sessions', schema=None) as batch_op:
        batch_op.drop_column('reminder_sent')
        batch_op.drop_column('meeting_link')

    with op.batch_alter_table('mentors', schema=None) as batch_op:
        batch_op.drop_column('default_meeting_link')
        batch_op.drop_column('mentor_group')
        batch_op.drop_column('participation_format')

    op.drop_table('group_topics')
    op.drop_table('activated_groups')
    with op.batch_alter_table('forwarded_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_fwd_target')
        batch_op.drop_index('ix_fwd_source')

    op.drop_table('forwarded_messages')
    # ### end Alembic commands ###
