"""add columns for handling telegram errors

Revision ID: 81f6c854432d
Revises: f51e8717a563
Create Date: 2026-02-23 00:33:31.748344

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "81f6c854432d"
down_revision: Union[str, Sequence[str], None] = "f51e8717a563"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create the PostgreSQL ENUM type that matches TelegramReasonNotInvited values
    telegram_enum = sa.Enum(
        "UNRESOLVABLE_USERNAME",
        "PRIVACY_RESTRICTED",
        "NOT_MUTUAL_CONTACT",
        "FLOOD_WAIT_EXHAUSTED",
        "MISCELLANEOUS",
        name="telegramreasonnotinvited",
    )
    telegram_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("participants", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("telegram_reason_not_invited", telegram_enum, nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "misc_reason_not_invited",
                sqlmodel.sql.sqltypes.AutoString(),
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("participants", schema=None) as batch_op:
        batch_op.drop_column("misc_reason_not_invited")
        batch_op.drop_column("telegram_reason_not_invited")
    # ### end Alembic commands ###

    # Drop the ENUM type created during upgrade
    telegram_enum = sa.Enum(
        "UNRESOLVABLE_USERNAME",
        "PRIVACY_RESTRICTED",
        "NOT_MUTUAL_CONTACT",
        "FLOOD_WAIT_EXHAUSTED",
        "MISCELLANEOUS",
        name="telegramreasonnotinvited",
    )
    telegram_enum.drop(op.get_bind(), checkfirst=True)
