"""remov category id from submission we would use join from teams to categories

Revision ID: be99dd684d6d
Revises: 11a82c0d6b6f
Create Date: 2026-02-26 00:00:25.910700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be99dd684d6d'
down_revision: Union[str, Sequence[str], None] = '11a82c0d6b6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_submissions_category_id'))
        batch_op.drop_constraint(batch_op.f('fk_team_submissions_category_id_categories'), type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_team_submissions_category_id_categories'), 'categories', ['category_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_team_submissions_category_id'), ['category_id'], unique=False)

    # ### end Alembic commands ###
