"""pending broadcasts

Revision ID: d17cdc616a7b
Revises: 9c7667f80cae
Create Date: 2026-02-23 11:05:30.098136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'd17cdc616a7b'
down_revision: Union[str, Sequence[str], None] = '9c7667f80cae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_broadcasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_pending_broadcasts_category_id_categories')),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], name=op.f('fk_pending_broadcasts_participant_id_participants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pending_broadcasts')),
    sa.UniqueConstraint('participant_id', 'category_id', name='uix_pending_broadcast_participant_category')
    )
    with op.batch_alter_table('pending_broadcasts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_broadcasts_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_broadcasts_participant_id'), ['participant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_broadcasts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_broadcasts_participant_id'))
        batch_op.drop_index(batch_op.f('ix_pending_broadcasts_category_id'))

    op.drop_table('pending_broadcasts')
    # ### end Alembic commands ###
