"""add column for tracking group membership

Revision ID: faffd48f7968
Revises: 23ae89ff1dfb
Create Date: 2026-02-21 23:27:31.863391

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "faffd48f7968"
down_revision: Union[str, Sequence[str], None] = "23ae89ff1dfb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("participants", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_telegram_group_member",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("participants", schema=None) as batch_op:
        batch_op.drop_column("is_telegram_group_member")

    # ### end Alembic commands ###
